[package]
name = "rust-captcha"
version = "0.0.1"
authors = ["daniele <git.daniele@gmail.com>"]

[dependencies]
log = "*"
env_logger = "*"
hyper = "*"

#getopts = "*"
#redis = "*"
#captcha = { git = "https://github.com/daniel-e/captcha-rs.git" }
