[package]
name = "rust-captcha"
version = "0.0.1"
authors = ["daniele <git.daniele@gmail.com>"]
build = "build.rs"

[build-dependencies]
pkg-config = "0.3.6"

#[dependencies.lodepng]
#git = "https://github.com/pornel/lodepng-rust.git"

[dependencies]
rustful = "*"
log = "*"
env_logger = "*"
getopts = "*"
rustc-serialize = "*"
rand = "*"
redis = "*"
libc = "*"
lodepng = "*"
