[package]
name = "rust-captcha"
version = "0.0.1"
authors = ["daniele <git.daniele@gmail.com>"]

[dependencies]
log = "0.3.7"
env_logger = "0.4.2"
rustful = "0.9.0"
base64 = "0.5.2"
serde_json = "1.0.2"
serde_derive = "1.0.7"
serde = "1.0.7"
redis = "0.8.0"
hyper = "0.10.10"
time = "0.1.37"
uuid = { version = "0.5.0", features = ["v4"] }
captcha = { git = "https://github.com/daniel-e/captcha.git" }
