[package]
name = "rust-captcha"
version = "0.0.1"
authors = ["daniele <git.daniele@gmail.com>"]

[dependencies]
log = "*"
env_logger = "*"
rustful = "*"
uuid = { version = "*", features = ["v4"] }
base64 = "*"
serde_json = "*"
serde_derive = "*"
serde = "*"
redis = "*"
captcha = { git = "https://github.com/daniel-e/captcha.git" }

#hyper = "*"
#getopts = "*"
